# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [27]:
import numpy as np

#Practice 1.1
#Create the following arrays
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2,5), dtype=int)
myarray1 = np.array([   [2.7, 0, -2], 
                        [3.4, 10.6, 0], 
                        [-19, 99.9, 13]])
myarray2 = np.arange(4, 4 * 15+1, 4).reshape(3, 5).astype(float)

#Display the arrays
print("Zeros Array:\n", zeros)
print("\nVowels Array:\n", vowels)
print("\nOnes Array:\n", ones)
print("\nMyarray1:\n", myarray1)
print("\nMyarray2:\n", myarray2)

Zeros Array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Vowels Array:
 ['a' 'e' 'i' 'o' 'u']

Ones Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

Myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [28]:
#Practice 1.2
import numpy as np

# Ensure the arrays are defined
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2,5), dtype=int)
myarray1 = np.array([   [2.7, 0, -2], 
                        [3.4, 10.6, 0], 
                        [-19, 99.9, 13]])
myarray2 = np.arange(4, 4 * 15+1, 4).reshape(3, 5).astype(float)

# Display Properties of the arrays
print(f"\nZeros Array:\n Dimension: {zeros.ndim}, Shape: {zeros.shape}, Size: {zeros.size}, Data Type: {zeros.dtype}, Item Size (bytes): {zeros.itemsize}")
print(f"\nVowels Array:\n Dimension: {vowels.ndim}, Shape: {vowels.shape}, Size: {vowels.size}, Data Type: {vowels.dtype}, Item Size (bytes): {vowels.itemsize}")
print(f"\nOnes Array:\n Dimension: {ones.ndim}, Shape: {ones.shape}, Size: {ones.size}, Data Type: {ones.dtype}, Item Size (bytes): {ones.itemsize}")
print(f"\nMyArray1 Array:\n Dimension: {myarray1.ndim}, Shape: {myarray1.shape}, Size: {myarray1.size}, Data Type: {myarray1.dtype}, Item Size (bytes): {myarray1.itemsize}")
print(f"\nMyArray2 Array:\n Dimension: {myarray2.ndim}, Shape: {myarray2.shape}, Size: {myarray2.size}, Data Type: {myarray2.dtype}, Item Size (bytes): {myarray2.itemsize}")
#Reshape the array of Ones
ones = ones.reshape(1, 10)
print(f"\nOnes Array Reshaped:\n {ones}")
#Dispay the 2nd and 3rd  element of the array of Vowels
print(f"\nVowels Array: 2nd and 3rd elements: {vowels[1:3]}")
#Display the 2nd and 3rd row of MyArray1
print(f"\nMyArray1 Array: 2nd and 3rd rows:\n {myarray1[1:3,:]}")
#Display the 1st and 2nd column of MyArray1
print(f"\nMyArray1 Array: 1st and 2nd columns:\n {myarray1[:,0:2]}")
#Display the 1st column of the 2nd and 3rd row of MyArray1
print(f"\nMyArray1 Array: 1st column of 2nd and 3rd rows:\n {myarray1[1:3, 0]}")
#Reverse the array Vowels
vowels = vowels[::-1]
print(f"\nVowels Array Reversed:\n {vowels}")


Zeros Array:
 Dimension: 1, Shape: (10,), Size: 10, Data Type: float64, Item Size (bytes): 8

Vowels Array:
 Dimension: 1, Shape: (5,), Size: 5, Data Type: <U1, Item Size (bytes): 4

Ones Array:
 Dimension: 2, Shape: (2, 5), Size: 10, Data Type: int64, Item Size (bytes): 8

MyArray1 Array:
 Dimension: 2, Shape: (3, 3), Size: 9, Data Type: float64, Item Size (bytes): 8

MyArray2 Array:
 Dimension: 2, Shape: (3, 5), Size: 15, Data Type: float64, Item Size (bytes): 8

Ones Array Reshaped:
 [[1 1 1 1 1 1 1 1 1 1]]

Vowels Array: 2nd and 3rd elements: ['e' 'i']

MyArray1 Array: 2nd and 3rd rows:
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

MyArray1 Array: 1st and 2nd columns:
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]

MyArray1 Array: 1st column of 2nd and 3rd rows:
 [  3.4 -19. ]

Vowels Array Reversed:
 ['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [29]:
#Practice 1.3
#Divide Ones by 3
ones_d = (ones / 3.0).astype(float)
print(f"\nOnes Array divided by 3:\n {ones_d}")
#Add MyArray1 and MyArray2
myarray3 = myarray1 + myarray2[:,:3]
print(f"\nMyArray1 + MyArray2:\n {myarray3}")
#Subtract MyArray1 from MyArray2
myarray4 = myarray2[:,:3] - myarray1
print(f"\nMyArray2 - MyArray1:\n {myarray4}")
#Multiply MyArray1 by MyArray2 elementwise
myarray5 = myarray1 * myarray2[:,:3]
print(f"\nMyArray1 * MyArray2:\n {myarray5}")
#Multiply MyArray1 by MyArray2 matrix multiplication
myarray6 = myarray1 @ myarray2[:,:3]
print(f"\nMyArray1 @ MyArray2:\n {myarray6}")
#Divide MyArray1 by MyArray2
myarray7 = myarray1 / myarray2[:,:3]
print(f"\nMyArray1 / MyArray2:\n {myarray7}")
#Raise MyArray1 to the power of 2 and divie by MyArray2
myarray8 = myarray1 ** 3 / 2
print(f"\nMyArray1 ** 3 / MyArray2:\n {myarray8}")
#Square root of MyArray2 and divide by 2
myarray9 = np.round(np.sqrt(myarray2) / 2, 2)
print(f"\nSqrt(MyArray2) / 2 rounded to 2 decimal places:\n {myarray9}")



Ones Array divided by 3:
 [[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333
  0.33333333 0.33333333 0.33333333 0.33333333]]

MyArray1 + MyArray2:
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]

MyArray2 - MyArray1:
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]

MyArray1 * MyArray2:
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]

MyArray1 @ MyArray2:
 [[ -77.2  -74.4  -71.6]
 [ 268.   324.   380. ]
 [2893.6 3269.2 3644.8]]

MyArray1 / MyArray2:
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]

MyArray1 ** 3 / MyArray2:
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]

Sqrt(MyArray2) / 2 rounded to 2 decimal places:
 [[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]]


Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [30]:
#Practice 1.4
#Find the transpose of Ones and MyArray2
print(f"\nTranspose of Ones:\n {ones.T}")
print(f"\nTranspose of MyArray2:\n {myarray2.T}")
#Sort the array of Vowels in reverse
print(f"\nSorted Vowels in reverse:\n {np.sort(vowels)[::-1]}")
#Sort MyArray1 by rows
print(f"\nSorted MyArray1 by rows:\n {np.sort(myarray1, axis=0)}")





Transpose of Ones:
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Transpose of MyArray2:
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]

Sorted Vowels in reverse:
 ['u' 'o' 'i' 'e' 'a']

Sorted MyArray1 by rows:
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [31]:
#Practice 1.5
#Create a splited array of 14 row and 3 columns into 3 arrays
myarray4_ = np.arange(-1, -1+14*3*0.25, 0.25).reshape(14,3)
print(f"\nMyArray4_:\n {np.array_split(myarray4_,3)}")



MyArray4_:
 [array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ]]), array([[2.75, 3.  , 3.25],
       [3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75],
       [5.  , 5.25, 5.5 ],
       [5.75, 6.  , 6.25]]), array([[6.5 , 6.75, 7.  ],
       [7.25, 7.5 , 7.75],
       [8.  , 8.25, 8.5 ],
       [8.75, 9.  , 9.25]])]


Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [32]:
#Practice 1.6
#Find the sum of all elements
print(f"\nSum of MyArray4_:\n {myarray4_.sum()}")
#Find the sum of all elements row wise
print(f"\nSum of MyArray4_ row wise:\n {myarray4_.sum(axis=1)}")
#Find the sum of all elements column wise
print(f"\nSum of MyArray4_ column wise:\n {myarray4_.sum(axis=0)}")
#Find the max of all elements
print(f"\nMax of MyArray4_:\n {myarray4_.max()}")
#Find the min of all elements in each row
print(f"\nMin of MyArray4_ row wise:\n {myarray4_.min(axis=1)}")
#Find the mean of all elements in each row
print(f"\nMean of MyArray4_ row wise:\n {myarray4_.mean(axis=1)}")
#Find the standard deviation column wise
print(f"\nStandard Deviation of MyArray4_ column wise:\n {myarray4_.std(axis=0)}")



Sum of MyArray4_:
 173.25

Sum of MyArray4_ row wise:
 [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]

Sum of MyArray4_ column wise:
 [54.25 57.75 61.25]

Max of MyArray4_:
 9.25

Min of MyArray4_ row wise:
 [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]

Mean of MyArray4_ row wise:
 [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]

Standard Deviation of MyArray4_ column wise:
 [3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [33]:
import pandas as pd

#Practice 2.1
cp = pd.read_csv('country-capital-lat-long-population.csv')
data = cp.to_numpy()
riyadh_l, riyadh_g = data[data[:, 0] == 'Saudi Arabia'][0][2:4].astype(float)
capital_c = data[:, 2:4].astype(float)
dist = np.sqrt(np.sum((capital_c - [riyadh_l, riyadh_g])**2, axis=1))
closest = np.argsort(dist)[1]
print(f"\nClosest Capital to Riyadh: {data[closest, 1]}")
print(f"Coordinates of Latitude and Longitude: {data[closest, 2:4]}") 




Closest Capital to Riyadh: Al-Manamah (Manama)
Coordinates of Latitude and Longitude: [26.2154 50.5832]


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [34]:
#Practice 2.2
import numpy as np
import pandas as pd

df = pd.read_csv('country-capital-lat-long-population.csv')
data = df.to_numpy()

us_aliases = ['United States', 'USA', 'U.S.A.', 'United States of America']
us_row = next((i for i in range(len(data)) if data[i, 0] in us_aliases), None)

if us_row is None:
    print("Error: United States not found in the data.")
else:
    us_coords = data[us_row, 2:4].astype(float)
    all_coords = data[:, 2:4].astype(float)
    distances = np.linalg.norm(all_coords - us_coords, axis=1)

    closest_indices = np.argpartition(distances, 11)[:11]
    closest_indices = closest_indices[closest_indices != us_row]
    
    print("\n1. Top 10 countries with capitals closest to Washington, DC:")
    for i, idx in enumerate(closest_indices, 1):
        print(f"{i}. {data[idx, 0]}")

    print("\n2. Coordinates of top 10 closest capitals:")
    print(all_coords[closest_indices])



1. Top 10 countries with capitals closest to Washington, DC:
1. Canada
2. Bahamas
3. Bermuda
4. Cuba
5. Turks and Caicos Islands
6. Cayman Islands
7. Haiti
8. Jamaica
9. Dominican Republic
10. Saint Pierre and Miquelon

2. Coordinates of top 10 closest capitals:
[[ 45.4166 -75.698 ]
 [ 25.0582 -77.3431]
 [ 32.2915 -64.778 ]
 [ 23.1195 -82.3785]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]
 [ 46.7738 -56.1815]]
