# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [3]:
import numpy as np

#Practice 1.1
#Create the following arrays
zeros = np.zeros(10)
vowels = np.array(['a', 'n', 'e', 'i', 'o', 'u'])
ones = np.ones((2,5), dtype=int)
myarray1 = np.array([   [2.7, 0, -2], 
                        [3.4, 10.6, 0], 
                        [-19, 99.9, 13]])
myarray2 = np.arange(4, 4 * 15+1, 4).reshape(3, 5).astype(float)

#Display the arrays
print("Zeros Array:\n", zeros)
print("\nVowels Array:\n", vowels)
print("\nOnes Array:\n", ones)
print("\nMyarray1:\n", myarray1)
print("\nMyarray2:\n", myarray2)

Zeros Array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Vowels Array:
 ['a' 'n' 'e' 'i' 'o' 'u']

Ones Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

Myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [1]:
#Practice 1.2
import numpy as np
# Display Properties of the arrays
print(f"\nZeros Array:\n Dimension: {zeros.ndim}, Shape: {zeros.shape}, Size: {zeros.size}, Data Type: {zeros.dtype}, Item Size (bytes): {zeros.itemsize}")
print(f"\nVowels Array:\n Dimension: {vowels.ndim}, Shape: {vowels.shape}, Size: {vowels.size}, Data Type: {vowels.dtype}, Item Size (bytes): {vowels.itemsize}")
print(f"\nOnes Array:\n Dimension: {ones.ndim}, Shape: {ones.shape}, Size: {ones.size}, Data Type: {ones.dtype}, Item Size (bytes): {ones.itemsize}")
print(f"\nMyArray1 Array:\n Dimension: {myarray1.ndim}, Shape: {myarray1.shape}, Size: {myarray1.size}, Data Type: {myarray1.dtype}, Item Size (bytes): {myarray1.itemsize}")
print(f"\nMyArray2 Array:\n Dimension: {myarray2.ndim}, Shape: {myarray2.shape}, Size: {myarray2.size}, Data Type: {myarray2.dtype}, Item Size (bytes): {myarray2.itemsize}")
#Reshape the array of Ones
ones = ones.reshape(1, 10)
print(f"\nOnes Array Reshaped:\n {ones}")
#Dispay the 2nd and 3rd  element of the array of Vowels
print(f"\nVowels Array: 2nd and 3rd elements: {vowels[1:3]}")
#Display the 2nd and 3rd row of MyArray1
print(f"\nMyArray1 Array: 2nd and 3rd rows:\n {myarray1[1:3,:]}")
#Display the 1st and 2nd column of MyArray1
print(f"\nMyArray1 Array: 1st and 2nd columns:\n {myarray1[:,0:2]}")
#Display the 1st column of the 2nd and 3rd row of MyArray1
print(f"\nMyArray1 Array: 1st column of 2nd and 3rd rows:\n {myarray1[1:3, 0]}")
#Reverse the array Vowels
vowels = vowels[::-1]
print(f"\nVowels Array Reversed:\n {vowels}")

NameError: name 'zeros' is not defined

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [28]:
#Practice 1.3
#Divide Ones by 3
ones_d = (ones / 3.0).astype(float)
print(f"\nOnes Array divided by 3:\n {ones_d}")
#Add MyArray1 and MyArray2
myarray3 = myarray1 + myarray2[:,:3]
print(f"\nMyArray1 + MyArray2:\n {myarray3}")
#Subtract MyArray1 from MyArray2
myarray4 = myarray2[:,:3] - myarray1
print(f"\nMyArray2 - MyArray1:\n {myarray4}")
#Multiply MyArray1 by MyArray2 elementwise
myarray5 = myarray1 * myarray2[:,:3]
print(f"\nMyArray1 * MyArray2:\n {myarray5}")
#Multiply MyArray1 by MyArray2 matrix multiplication
myarray6 = myarray1 @ myarray2[:,:3]
print(f"\nMyArray1 @ MyArray2:\n {myarray6}")
#Divide MyArray1 by MyArray2
myarray7 = myarray1 / myarray2[:,:3]
print(f"\nMyArray1 / MyArray2:\n {myarray7}")
#Raise MyArray1 to the power of 2 and divie by MyArray2
myarray8 = myarray1 ** 3 / myarray2[:,:3]
print(f"\nMyArray1 ** 3 / MyArray2:\n {myarray8}")
#Square root of MyArray2 and divide by 2
myarray9 = np.round(np.sqrt(myarray2) / 2, 2)
print(f"\nSqrt(MyArray2) / 2 rounded to 2 decimal places:\n {myarray9}")



Ones Array divided by 3:
 [[2.09075158e-07 2.09075158e-07 2.09075158e-07 2.09075158e-07
  2.09075158e-07 2.09075158e-07 2.09075158e-07 2.09075158e-07
  2.09075158e-07 2.09075158e-07]]

MyArray1 + MyArray2:
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]

MyArray2 - MyArray1:
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]

MyArray1 * MyArray2:
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]

MyArray1 @ MyArray2:
 [[ -77.2  -74.4  -71.6]
 [ 268.   324.   380. ]
 [2893.6 3269.2 3644.8]]

MyArray1 / MyArray2:
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]

MyArray1 ** 3 / MyArray2:
 [[ 4.92075000e+00  0.00000000e+00 -6.66666667e-01]
 [ 1.63766667e+00  4.25362857e+01  0.00000000e+00]
 [-1.55886364e+02  2.07708958e+04  4.22500000e+01]]

Sqrt(MyArray2) / 2 rounded to 2 decimal places:
 [[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.7

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [9]:
# Write your answer here




Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [10]:
# Write your ansewr here




#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [11]:
# Write your answer here



#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [12]:
# Write your answer here

